### ISSUE TITLE
CGI Script

### ISSUE THREAD

**Issue by todouu** [XZES40/XZES40-Transformer#10]
Create a script to accept an HTTP request with an XML and XSL file, call Transformer with these files, and return the new XML file or an appropriate error.

- [x] Create the Python CGI script.
- [x] Test the application.
- [x] Document the API.
- [ ] Update the design document if needed.

Target development time: February 27, 2017 - March 6, 2017

**Comment by shathaway** [comment]
The easiest Apache HTTPD modules to use are: mod_cgi and mod_cgid.  Another module I have used with Python (installation of Edgewall TRAC project) is the mod_wsgi module.  See the Apache HTTPD documentation on how to configure these modules.

**Comment by pop** [comment]
Resolved by #35
