### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by todouu** [XZES40/XZES40-Transformer#11]
Create a web interface for the HTTP CGI script API.

- [ ] Create a website for users to access the website through the CGI script API.
- [ ] Create a form for users to upload XML and XSL documents and download a transformed XML document.
- [ ] Handle errors correctly.
- [ ] Ensure this works with a running Apache server.
- [ ] Update the design document if needed.

Target development time: March 6, 2017 - March 20, 2017

**Comment by pop** [comment]
Resolved in #33
