### ISSUE TITLE
Week 3 Development

### ISSUE THREAD

**Issue by pop** [XZES40/XZES40-Transformer#18]
Below are the goals we each intend to complete during this week of development:

All:

- [x] Meet with Client (Steven Hathaway)

@Todopen 

- [x] Completing the Document class.
- [x] Completing the Transform class.
- [x] Investigating why the document transformer causes a Segmentation Fault.

@zixunlu 

- [x] Learn Git.
- [x] Set up a working development environment.
- [x] Be familiarized with the Xalan and Xerces C++ libraries.
- [x] Complete the benchmark tests.

@elijahcaine

- [x] Help with finishing the basic functionality features.
- [x] Setup an automated testing infrastructure.
- [x] Continue to get @Todopen and @zixunlu up to date on the project.
- [x] Review active Pull Requests.

**Comment by shathaway** [comment]
You need to start prototyping various modules to test the various features. The prototypes do not need to be a complete integration, they are for learning and qualifying the various interfaces.  Code from the prototypes can then be integrated into a more complete project.  This allows for rapid development along with quality assurance of your integration efforts.  The team efforts of collaboration are required to refine the code and product integration issues.

I have supplied some code you can strip and re-use in your prototype efforts.

**Comment by pop** [comment]
@shathaway Can you elaborate on what you mean by "Start prototyping various modules to test the various features"? What would be an example of this?

I saw your addition of the code examples. Thank you for those, I am sure they will be very helpful.

**Comment by shathaway** [comment]
The purpose of prototype modules is for studying and proving specific features of your project.  The prototypes demonstrate the effectiveness of the various decisions to be made in the construction of your project.  The prototypes do not need to be the final project. Features of the prototypes can be re-coded to implement the necessary parts of the project.  When you prove the effectiveness of your prototypes, you can relatively assure correct operation of those features in your project.

Hope this discussion helps! - Steve
