### ISSUE TITLE
OS-Agnostic API

### ISSUE THREAD

**Issue by pop** [XZES40/XZES40-Transformer#19]
The application needs to ensure that it can run on any operating system so it is not tied exclusively to Debian.

- [ ] Write the os-agnostic API library, or find and adopt an existing one.
- [ ] Test this library and ensure it works on our supported platforms.
- [ ] Update the design document if needed.

Target development time: Ongoing

**Comment by shathaway** [comment]
I have added some example 'C' code in capstone/demo-code for your review.  The ICU, Xerces and Xalan libraries are already multiple-platform compliant.

I have added some items in capstone/docs and capstone/tools in the Transformer project you may be interested in using or modifying.
