### ISSUE TITLE
Choose one: C or C++

### ISSUE THREAD

**Issue by pop** [XZES40/XZES40-Transformer#2]
@Todopen @zixunlu Xerces offers a C API which we *can* use. On my branch `project-structure` (Pull Request #1) I have a C example and a C++ example which you can take a look at.

I would like to start a discussion to decide if we write the transformer in C or C++. This will require us to write the caching system (or the Redis interface) in C and to use C libraries for multi-threaded tasks. My responsibilities are limited after getting the initial project setup so I don't really care if we use C or C++, but I do prefer C for what it is worth.

@shathaway Your input would be appreciated in this. If you have a preference for us to use one language over the other we will choose that one. I am biased for the use of C but of course I am willing to use C++ :smile: 

## Related materials:

- [Xerces C API reference](https://xalan.apache.org/xalan-c/apiDocs/XalanCAPI_8h.html)
- [Basic Xerces Usage Overview](https://xalan.apache.org/xalan-c/usagepatterns.html)  (includes C and C++ usage)
- [My branch](https://github.com/XZES40/XZES40-Transformer/tree/project-structure)
- [Simple C implementation](/XZES40/XZES40-Transformer/blob/project-structure/xzes40/transformer/src/xzes40.c)
- [Simple C++ implementation](/XZES40/XZES40-Transformer/blob/project-structure/xzes40/transformer/src/xzes40.cpp)

**Comment by zixunlu** [comment]
I prefer use C and I wil take a look at.

2016年12月31日星期六，Elijah Caine <notifications@github.com> 写道：

**Comment by shathaway** [comment]
FYI
The Xerces C-API is a wrapper that calls the C++ transformations.

An application can be C or C++ based, but the heavy work is done in the
C++ code.

Steven J. Hathaway

**Comment by todouu** [comment]
I prefer to C++,but both of them is OK. I don't care this problem too.

**Comment by pop** [comment]
@Todopen Have you tested the application code I wrote?

**Comment by todouu** [comment]
Not yet, I just come back US today.

**Comment by todouu** [comment]
@ElijahCaine I will test the code during this weekend.

**Comment by pop** [comment]
@Todopen I have moved the C code to an `examples` directory in the transformer source code tree. If you want to run it you will need to figure out how to compile it manually by looking at how the Makefile works.
