### ISSUE TITLE
Discussion - Cache Management - Execution Contexts

### ISSUE THREAD

**Issue by shathaway** [XZES40/XZES40-Transformer#20]
### Your C++ class structure could handle some significant upgrades.

**Cache_Entity -- needs to be enhanced with a searchable list structure**
  Next_Cache_Entity -> linked list
  Transform Context (reusable)
  File_URL
  Document-Type(DTD, DOCTYPE, TRANSFORM, SCHEMA, ,,,)
  Processor-Reference
    Working Process
    Working Thread
  Compiled Transform Reference (reusable)
  Parsed Document Reference (reusable)

**XML String Types -- work with these classes**
  The default internal encoding for Xerces/Xalan are 16-bit entities (UTF-16).
  Some Linux systems use 32-bit elements for multi-byte string transfer functions.
  Most systems use 16-bit elements for multi-byte string transfer functions.

  The derived string classes for ICU, Xerces, Xalan implement 32-bit methods
  in their unicode compliant string classes.

## Memory Management Contexts
  The Xerces parsers and Xalan transformations have engines to manage context
  and factories that generate complex elements.  The elements generated by the
  factories are owned by the factories unless a caller requests obtaining
  ownership of object instead of reference to object.

The objects created by the Xalan and Xerces factories use their own heap
memory management by overloading the NEW and DELETE operators.  The extensions
are maintained by inventive use of STL (Symbolic Template Library) macros.

**Comment by pop** [comment]
@todouu Please review this issue. It seems useful for your tasks.
