### ISSUE TITLE
Only Cache Stylesheets

### ISSUE THREAD

**Issue by pop** [XZES40/XZES40-Transformer#24]
@shathaway @Todopen @zixunlu Please Comment

In our meeting last week with Steven it became apparent that the only documents which are regularly reused are stylesheets.
If use use this to our advantage, we can create a document transformer which *only* caches stylesheets. This saves us development time trying to cache *all* objects.

Thoughts? If we implement this we need to start refactoring the code soon.

**Comment by zixunlu** [comment]
I agree with you.

**Comment by todouu** [comment]
It true save our development time, I think we can just cache the style sheet.

**Comment by shathaway** [comment]
The stylesheets are good for caching.

If you will be implementing top-level parameters including document
fragments, then those fragments may also need to be cached.

The KeyList library is useful for handling cached products.

Sincerely,
Steven J. Hathaway

**Comment by pop** [comment]
@shathaway Can you elaborate on what you mean by "You will be implementing top-level parameters including document fragments"? I know we do not have a thorough understanding of what that means.

If you are able to, can you link us to some good documentation on the KeyList library and its usage?

**Comment by todouu** [comment]
@ElijahCaine @zixunlu @shathaway  If we only cache the stylesheet, can we skip to parse the xml file to DOM object? because we don't need cache it, we can just using xalan to automatically parse. If we do, I think we need change lots, because we are using XercesDOMwapper to do the xalan transformation.

**Comment by pop** [comment]
@Todopen I think parsing the xml file into a dom object is the safest thing to do.

**Comment by shathaway** [comment]
There is a build sample in the Xalan-C source repository that illustrates how to implement and manage top-level parameters associated with stylesheets.

**Comment by pop** [comment]
We will be caching XML and XSL documents.
