### ISSUE TITLE
Parallel Computation

### ISSUE THREAD

**Issue by todouu** [XZES40/XZES40-Transformer#7]
Perform and optimize parallel document transformation.

- [x] Decide on a library to use to perform parallel computation.
- [x] Implement parallel transformation.
- [x] Ensure that this increases performance.
- [x] Update the design document if needed.

Target development time: January 30, 2017 - March 20, 2017

**Comment by todouu** [comment]
@ElijahCaine @shathaway @zixunlu  Should we using POSIX thread (pthread) libraries to perform parallel computation?

**Comment by pop** [comment]
@Todopen The design document specifies another document. You should look into using that one instead, but POSIX threads are very well supported and @shathaway (or Kevin McGrath) should be able to help you with learning it more than the library we chose.
